"""Generate the synthetic-data documentation (Stage 2).

Writes two Markdown artifacts from the live generated data so they never drift:
- ``data/synthetic_enrichment/README.md`` — the schema of each file.
- ``reports/data-generation.md`` — process, seeds, hypotheses, limitations, risks,
  plus summary statistics including the oracle optimal-arm distribution by
  segment (the evidence that justifies a contextual policy).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

from aep.config import REPO_ROOT
from aep.data.loader import load_processed
from aep.synthetic.catalog import OFFER_IDS, OFFERS, eligibility_mask
from aep.synthetic.config import (
    CENSOR_WINDOW_DAYS,
    HORIZON_DAYS,
    MASTER_SEED,
    N_EVENTS,
    SEED_DELAY,
    SEED_EVENTS,
    SEED_REWARD_MODEL,
)
from aep.synthetic.features import CONTEXT_FEATURES, Standardizer, build_context_matrix
from aep.synthetic.generate import load_synthetic
from aep.synthetic.reward_model import RewardModel

SCHEMA_README_PATH = REPO_ROOT / "data" / "synthetic_enrichment" / "README.md"
DATA_GENERATION_PATH = REPO_ROOT / "reports" / "data-generation.md"


def _oracle_optimal_by_segment(events: pd.DataFrame) -> pd.DataFrame:
    """For each event, the eligible arm with the highest true reward prob."""
    base = load_processed()
    clients = base.iloc[events["client_idx"].to_numpy()].reset_index(drop=True)
    X, _ = build_context_matrix(clients, Standardizer.fit(base))
    subscribed = clients["subscribed"].to_numpy().astype(float)

    rm = RewardModel.build()
    r = rm.reward_prob(X, subscribed)  # (n, n_offers)
    elig = eligibility_mask(clients)
    r = np.where(elig, r, -1.0)
    best = r.argmax(axis=1)
    df = pd.DataFrame(
        {"segment": events["segment"].to_numpy(), "best_offer": [OFFER_IDS[b] for b in best]}
    )
    return (
        df.groupby("segment")["best_offer"]
        .agg(lambda s: s.value_counts().idxmax())
        .rename("dominant_optimal_offer")
        .reset_index()
    )


def write_schema_readme(path: Path = SCHEMA_README_PATH) -> Path:
    lines = [
        "# Synthetic enrichment — file schemas",
        "",
        "> Generated by `aep synth report`. Artifacts (`*.parquet`, `*.json`) are",
        "> git-ignored; regenerate with `aep synth generate`. Physically separate",
        "> from the Kaggle base: these are an invented commercial/experimentation",
        "> layer, grounded in the base only through context features and the real",
        "> subscription signal.",
        "",
        "## `offer_catalog.parquet` — the bandit arms",
        "",
        "| Column | Type | Description |",
        "|--------|------|-------------|",
        "| `offer_id` | str | Arm identifier (O1..O8). |",
        "| `name` | str | Human-readable offer name. |",
        "| `product` | str | Product family (term_deposit, credit_card, ...). |",
        "| `channel` | str | Delivery channel (cellular, telephone, app_push, email). |",
        "| `message_tone` | str | Framing (informative, urgency, social_proof, reward). |",
        "| `base_appeal` | float | Latent baseline conversion logit (pre-context). |",
        "| `eligibility` | str | Human-readable suitability rule. |",
        "",
        "## `offer_events.parquet` — logged impressions (one row per decision)",
        "",
        "| Column | Type | Description |",
        "|--------|------|-------------|",
        "| `event_id` | int | Unique impression id. |",
        "| `day` | int | Day of the impression in [0, horizon). |",
        "| `client_idx` | int | Row index into the processed base (context reference). |",
        "| `segment` | str | Synthetic fairness segment (age band x white-collar). |",
        "| `subscribed` | int | Real Bank Marketing subscription signal (context feature). |",
        "| `offer_id` | str | **Logged action**: the arm actually shown. |",
        "| `n_eligible` | int | Number of eligible arms for this client. |",
        "| `propensity` | float | P(action) under the logging policy = 1 / n_eligible. |",
        "| `click` | int | Immediate (intermediate) reward: 1 if clicked. |",
        "",
        "## `delayed_rewards.parquet` — final reward realization",
        "",
        "| Column | Type | Description |",
        "|--------|------|-------------|",
        "| `event_id` | int | Joins to `offer_events`. |",
        "| `conversion` | int | **Final reward**: 1 if converted (requires a click). |",
        "| `reward_delay_days` | int | Days until the reward is observable. |",
        "| `reward_available_day` | int | `day + delay` (converter) or `day + censor` (else). |",
        "| `censored` | bool | True for non-converters (reward known to be 0 at horizon). |",
        "",
        "## `reward_model_params.json` / `context_standardizer.json`",
        "",
        "The frozen oracle reward parameters and the numeric-feature standardizer,",
        "persisted for reproducibility and reuse by the bandits/service.",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_data_generation_report(path: Path = DATA_GENERATION_PATH) -> Path:
    data = load_synthetic()
    events, delayed = data["offer_events"], data["delayed_rewards"]
    joined = events.merge(delayed, on="event_id")

    overall_click = events["click"].mean()
    overall_conv = delayed["conversion"].mean()

    per_offer = (
        joined.groupby("offer_id")
        .agg(
            exposure=("event_id", "size"),
            click_rate=("click", "mean"),
            conv_rate=("conversion", "mean"),
        )
        .reindex(OFFER_IDS)
    )
    per_segment = (
        joined.groupby("segment")
        .agg(exposure=("event_id", "size"), conv_rate=("conversion", "mean"))
        .sort_values("exposure", ascending=False)
    )
    conv_delays = delayed.loc[delayed["conversion"] == 1, "reward_delay_days"]
    optimal_by_seg = _oracle_optimal_by_segment(events)

    lines = [
        "# Synthetic data generation report",
        "",
        f"_Generated on {date.today().isoformat()} by `aep synth report`._",
        "",
        "## 1. Purpose",
        "",
        "The Bank Marketing base has no offers, no channels and no bandit feedback. "
        "This layer **synthesizes** a commercial experimentation environment on top "
        "of the factual context so we can study exploration vs. exploitation without "
        "any real client data. It is **physically separate** from the Kaggle base.",
        "",
        "## 2. Process & seeds (reproducible)",
        "",
        f"- **Master seed:** `{MASTER_SEED}` (sub-seeds: reward_model=`{SEED_REWARD_MODEL}`, "
        f"events=`{SEED_EVENTS}`, delay=`{SEED_DELAY}`).",
        f"- **Impressions:** {N_EVENTS:,} over a **{HORIZON_DAYS}-day** horizon.",
        f"- **Arms:** {len(OFFERS)} offers (product x channel x tone) with eligibility rules.",
        "- **Context:** " f"{len(CONTEXT_FEATURES)} features ({', '.join(CONTEXT_FEATURES)}).",
        "- **Reward funnel:** `click ~ Bernoulli(p_click(context, offer))`, then "
        "`conversion ~ Bernoulli(p_conv(context, offer))` only if clicked. "
        "`p_conv` is boosted by the client's real subscription signal for "
        "deposit-like products (keeping the layer grounded).",
        "- **Logging policy:** uniform over eligible offers, so the recorded "
        "`propensity = 1 / n_eligible` is exact (enables unbiased off-policy eval).",
        f"- **Delayed rewards:** converters realize after `1 + Poisson(lambda_product)` "
        f"days; non-converters are censored at **{CENSOR_WINDOW_DAYS} days**.",
        "",
        "## 3. Summary statistics",
        "",
        f"- Overall click rate: **{overall_click:.2%}** | conversion rate: "
        f"**{overall_conv:.2%}**.",
        f"- Mean eligible arms per impression: **{events['n_eligible'].mean():.2f}** "
        f"(of {len(OFFERS)}).",
        f"- Converter delay (days): mean **{conv_delays.mean():.1f}**, "
        f"median **{conv_delays.median():.0f}**, max **{conv_delays.max():.0f}**.",
        "",
        "### Per-offer exposure and rates",
        "",
        "| Offer | Exposure | Click rate | Conversion rate |",
        "|-------|----------|------------|-----------------|",
    ]
    for oid, row in per_offer.iterrows():
        lines.append(
            f"| `{oid}` | {int(row['exposure']):,} | {row['click_rate']:.2%} | "
            f"{row['conv_rate']:.2%} |"
        )
    lines += [
        "",
        "### Per-segment exposure and conversion",
        "",
        "| Segment | Exposure | Conversion rate |",
        "|---------|----------|-----------------|",
    ]
    for seg, row in per_segment.iterrows():
        lines.append(f"| `{seg}` | {int(row['exposure']):,} | {row['conv_rate']:.2%} |")

    lines += [
        "",
        "### Oracle optimal arm by segment (why context matters)",
        "",
        "The best arm (highest true reward prob, among eligible) **differs across "
        "segments** — a context-free policy cannot capture this, motivating the "
        "contextual bandit in Stage 3.",
        "",
        "| Segment | Dominant optimal offer |",
        "|---------|------------------------|",
    ]
    for _, row in optimal_by_seg.iterrows():
        lines.append(f"| `{row['segment']}` | `{row['dominant_optimal_offer']}` |")

    lines += [
        "",
        "## 4. Hypotheses encoded",
        "",
        "- Conversion is **heterogeneous by segment** (age, education, occupation, "
        "previous-campaign outcome).",
        "- Channels differ in engagement (app_push > cellular > telephone > email "
        "for click), with age interactions.",
        "- Premium/investment products suit older, white-collar, educated segments; "
        "loans suit younger segments.",
        "- Rewards are **delayed** and **censored**, so naive immediate-reward "
        "estimates are biased early (cold-start).",
        "",
        "## 5. Limitations & risks",
        "",
        "- The oracle is a **modeling assumption**, not reality; absolute rates are "
        "not meaningful, only *relative* policy comparisons are.",
        "- Using the real subscription label as receptiveness couples the synthetic "
        "layer to one base; do not interpret as causal product demand.",
        "- Uniform logging maximizes off-policy validity but is not how a real "
        "system would log; a deployed logger needs its own propensity tracking.",
        "- **Reward hacking risk:** a policy could over-exploit the highest-base arm; "
        "Stage 4 guardrails and fairness checks address this.",
        "- No protected attributes are used; `segment` is a synthetic construct for "
        "exposure analysis only.",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
